export enum orderStatus {
  INITIATED = "INITIATED",
  CONFIRMED = "CONFIRMED",
  CANCELED = "CANCELED",
  DECLINED = "DECLINED",
  COMPLETED = "COMPLETED",
  RETURN_INITIATED = "RETURN_INITIATED",
  RETURN_COMPLETED = "RETURN_COMPLETED",
  REFUND_INITIATED = "REFUND_INITIATED",
  REFUND_COMPLETED = "REFUND_COMPLETED",
}

export enum transactionStatus {
  INITIATED = "INITIATED",
  SUCCESS = "SUCCESS",
  CANCELED = "CANCELED",
  DECLINED = "DECLINED",
  FAILED = "FAILED",
  PENDING = "PENDING",
}
